### PR TITLE
Initial Pandaproxy Deployment

### PR DESCRIPTION
**Pull request by BenPope**
Note: This only supports replicas: 1

Based on #22 for dependencies

TODO:
* Switch from `LoadBalancer` to `Ingress`
* Expose route based on `advertised_address`
* Maybe it should be a `StatefulSet`?

### CODE REVIEW

**Comment by senior7515** [comment]
i don't think this makes sense since we'll add the proxy to the redpanda binary img.

**Comment by dotnwat** [comment]
> i don't think this makes sense since we'll add the proxy to the redpanda binary img.

can you say a little more? it seems like deployment scenarios are distinct from packaging, so maybe you're implying something about a unified helm chart or unified operator for both modes of operation?

**Comment by senior7515** [comment]
> > i don't think this makes sense since we'll add the proxy to the redpanda binary img.
> 
> can you say a little more? it seems like deployment scenarios are distinct from packaging, so maybe you're implying something about a unified helm chart or unified operator for both modes of operation?

from the demo today, basically our kubernetes operator is a stateful set. so ben wanted to have a stateful set for the proxy. once the redpanda binary has an option `config.enable_http_proxy` then it gets the same deployment model in k8s without additional sidecars.

**Comment by BenPope** [comment]
> from the demo today, basically our kubernetes operator is a stateful set. so ben wanted to have a stateful set for the proxy. 

I think the proxy should be a `StatefulSet` because the instances have "identity", that is, it matters which one a client connects to.

I think there are trade-offs in running it standalone or embedded in Redpanda.

I wrote the code for the demo, for local testing, and possibly for other integration test scenarios, such as running it against a Kafka cluster. I left this PR as draft because it's not finished work, it's just what I had and wanted to publish it.

**Comment by dotnwat** [comment]
> > > i don't think this makes sense since we'll add the proxy to the redpanda binary img.
> > 
> > 
> > can you say a little more? it seems like deployment scenarios are distinct from packaging, so maybe you're implying something about a unified helm chart or unified operator for both modes of operation?
> 
> from the demo today, basically our kubernetes operator is a stateful set. so ben wanted to have a stateful set for the proxy. once the redpanda binary has an option `config.enable_http_proxy` then it gets the same deployment model in k8s without additional sidecars.

This what I thought you had in mind. I think it makes sense; I'll be curious to see if there are conflicts arise: things that an operator may do for a redpanda statefulset may not be relevant for a proxy layer, especially when it comes to upgrade procedure and day 2 ops.

**Comment by BenPope** [comment]
Not required due to https://github.com/vectorizedio/redpanda/pull/682

**Pull request closed without merging**
